# -*- coding: utf-8 -*-
"""akbankProje.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gzYmFdigfyjdGtm3eOvba_fcdqdliqdy
"""

import csv
import datetime
import pandas as pd


with open("Menu.txt", "w") as menu_file:
    menu_file.write("* Lütfen Bir Pizza Tabanı Seçiniz:\n1: Klasik\n2: Margarita\n3: TürkPizza\n4: Sade Pizza\n* ve seçeceğiniz sos:\n11: Zeytin\n12: Mantarlar\n13: Keçi Peyniri\n14: Et\n15: Soğan\n16: Mısır\n* Teşekkür ederiz!")

class Pizza:
    def __init__(self):
        self._description = "Pizza"
        self._cost = 0

    def get_description(self):
        return self._description

    def get_cost(self):
        return self._cost

class KlasikPizza(Pizza):
    def __init__(self):
        super().__init__()
        self._description = "Klasik Pizza"
        self._cost = 40.00


class MargaritaPizza(Pizza):
    def __init__(self):
        super().__init__()
        self._description = "Margarita Pizza"
        self._cost = 52.00


class TurkPizza(Pizza):
    def __init__(self):
        super().__init__()
        self._description = "Türk Pizza"
        self._cost = 58.00


class SadePizza(Pizza):
    def __init__(self):
        super().__init__()
        self._description = "Sade Pizza"
        self._cost = 35.00

class Decorator(Pizza):
    def __init__(self, pizza):
        super().__init__()
        self._pizza = pizza

    def get_description(self):
        return self._pizza.get_description() + ", " + self._description

    def get_cost(self):
        return self._pizza.get_cost() + self._cost


class Zeytin(Decorator):
    def __init__(self, pizza):
        super().__init__(pizza)
        self._description = "Zeytin"
        self._cost = 5.00


class Mantar(Decorator):
    def __init__(self, pizza):
        super().__init__(pizza)
        self._description = "Mantar"
        self._cost = 6.50


class KeciPeyniri(Decorator):
    def __init__(self, pizza):
        super().__init__(pizza)
        self._description = "Keçi Peyniri"
        self._cost = 9.00


class Et(Decorator):
    def __init__(self, pizza):
        super().__init__(pizza)
        self._description = "Et"
        self._cost = 12.50


class Sogan(Decorator):
    def __init__(self, pizza):
        super().__init__(pizza)
        self._description = "Soğan"
        self._cost = 4.00


class Misir(Decorator):
    def __init__(self, pizza):
        super().__init__(pizza)
        self._description = "Misir"
        self._cost = 6.00

def main():
    # Menu.txt dosyasından menüyü oku ve yazdır
    with open('Menu.txt', 'r') as f:
        menu = f.read()
    print(menu)

    # Kullanıcıdan pizza ve sos seçimini al
    pizza_choice = input("Lütfen pizza seçiminizi yapınız (1-4): ")
    sos_choice = input("Lütfen sos seçiminizi yapınız (11-16): ")

    # Seçilen pizzayı oluştur
    if pizza_choice == '1':
        pizza = KlasikPizza()
    elif pizza_choice == '2':
        pizza = MargaritaPizza()
    elif pizza_choice == '3':
        pizza = TurkPizza()
    elif pizza_choice == '4':
        pizza = SadePizza()
    else:
        print("Geçersiz pizza seçimi!")
        return

    # Seçilen sosu pizzaya ekle
    if sos_choice == '11':
        pizza = Zeytin(pizza)
    elif sos_choice == '12':
        pizza = Mantar(pizza)
    elif sos_choice == '13':
        pizza = KeciPeyniri(pizza)
    elif sos_choice == '14':
        pizza = Et(pizza)
    elif sos_choice == '15':
        pizza = Sogan(pizza)
    elif sos_choice == '16':
        pizza = Misir(pizza)
    else:
        print("Geçersiz sos seçimi!")
        return

    # Toplam fiyatı hesapla
    total_cost = pizza.get_cost()
    description = pizza.get_description()

    # Kullanıcı bilgilerini al
    name = input("İsim: ")
    id_number = input("TC Kimlik Numarası: ")
    cc_number = input("Kredi Kartı Numarası: ")
    cc_password = input("Kredi Kartı Şifresi: ")

    # Sipariş özetini yazdır
    print(f"{name}, {description} siparişiniz {total_cost} TL tutarındadır.")
    print("Teşekkür ederiz!")

    # Yeni bir veri çerçevesi oluşturalım
    yeni_siparis = pd.DataFrame({
    "Kullanıcı Adı": [name],
    "Kullanıcı Kimliği": [id_number],
    "Kredi Kartı Bilgileri": [cc_number],
    "Kredi Kartı Şifresi": [cc_password],
    "Sipariş Açıklaması": [description],
    "Sipariş Zamanı": [datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")]  
    })

    # Yeni siparişi Orders_Database.csv dosyasına ekleyelim
    orders_df = pd.concat([yeni_siparis], ignore_index=True)
    orders_df.to_csv("Orders_Database.csv", index=False)

if __name__ == '__main__':
    main()